"""remove fields to ParsedCaseDetails

Revision ID: 226bf206708a
Revises: f6545d825b28
Create Date: 2025-08-06 20:05:05.406933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226bf206708a'
down_revision = 'f6545d825b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsed_case_details', schema=None) as batch_op:
        batch_op.drop_column('case_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsed_case_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
