"""Add raw_response to CaseQuery

Revision ID: 285bd33ab094
Revises: e77989c685d6
Create Date: 2025-08-10 19:49:05.225858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285bd33ab094'
down_revision = 'e77989c685d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_pdf_link', sa.String(length=300), nullable=True))

    with op.batch_alter_table('parsed_case_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_pdf_link', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsed_case_details', schema=None) as batch_op:
        batch_op.drop_column('order_pdf_link')

    with op.batch_alter_table('case_queries', schema=None) as batch_op:
        batch_op.drop_column('latest_pdf_link')

    # ### end Alembic commands ###
