"""Add remark column

Revision ID: 319d29ffb87b
Revises: 8736a592362c
Create Date: 2025-08-08 00:51:35.423840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319d29ffb87b'
down_revision = '8736a592362c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsed_case_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Remark', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsed_case_details', schema=None) as batch_op:
        batch_op.drop_column('Remark')

    # ### end Alembic commands ###
