"""Remove RawResponse table

Revision ID: 8528ae07fc33
Revises: 9b676bf441d8
Create Date: 2025-08-06 17:03:19.250955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8528ae07fc33'
down_revision = '9b676bf441d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_responses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('html_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fetched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['case_queries.id'], name=op.f('raw_responses_query_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('raw_responses_pkey'))
    )
    # ### end Alembic commands ###
