"""Remove column case esrtiblished

Revision ID: 8736a592362c
Revises: 226bf206708a
Create Date: 2025-08-06 21:24:19.137790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8736a592362c'
down_revision = '226bf206708a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_queries', schema=None) as batch_op:
        batch_op.drop_column('court_establishment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('court_establishment', sa.VARCHAR(length=150), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
