"""updated new fields to CaseQuery &  ParsedCaseDetails

Revision ID: bd00814dcd5a
Revises: 8528ae07fc33
Create Date: 2025-08-06 17:32:39.320145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd00814dcd5a'
down_revision = '8528ae07fc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('district', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('court_complex', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('court_establishment', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('from_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('to_date', sa.String(length=20), nullable=True))
        batch_op.alter_column('case_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('case_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('parsed_case_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('filing_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('registration_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('registration_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('judgment_date', sa.String(length=20), nullable=True))
        batch_op.drop_column('latest_pdf_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsed_case_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_pdf_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('judgment_date')
        batch_op.drop_column('status')
        batch_op.drop_column('registration_date')
        batch_op.drop_column('registration_number')
        batch_op.drop_column('filing_number')
        batch_op.drop_column('case_type')

    with op.batch_alter_table('case_queries', schema=None) as batch_op:
        batch_op.alter_column('case_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('case_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('to_date')
        batch_op.drop_column('from_date')
        batch_op.drop_column('court_establishment')
        batch_op.drop_column('court_complex')
        batch_op.drop_column('district')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
