"""Add raw_response to CaseQuery

Revision ID: e77989c685d6
Revises: 319d29ffb87b
Create Date: 2025-08-10 17:06:46.598537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77989c685d6'
down_revision = '319d29ffb87b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_response', sa.Text(), nullable=True))

    with op.batch_alter_table('parsed_case_details', schema=None) as batch_op:
        batch_op.alter_column('Remark',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsed_case_details', schema=None) as batch_op:
        batch_op.alter_column('Remark',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('case_queries', schema=None) as batch_op:
        batch_op.drop_column('raw_response')

    # ### end Alembic commands ###
