"""updated new fields to CaseQuery &  ParsedCaseDetails

Revision ID: f6545d825b28
Revises: bd00814dcd5a
Create Date: 2025-08-06 17:44:01.594746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6545d825b28'
down_revision = 'bd00814dcd5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_queries', schema=None) as batch_op:
        batch_op.drop_column('to_date')
        batch_op.drop_column('from_date')

    with op.batch_alter_table('parsed_case_details', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('filing_number')
        batch_op.drop_column('filing_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsed_case_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filing_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('filing_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('case_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('to_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
